version: '3.9'

services:
  db:
    image:  postgres:13-alpine
    ports:
      - '5430:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - fullstack_demo_pg_data:/var/lib/postgresql/data/

    networks:
      fullstackdemo:
        aliases:
          - fullstackdemo-db.local

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

    networks:
      fullstackdemo:
        aliases:
          - fullstackdemo-frontend.local

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db

    networks:
      fullstackdemo:
        aliases:
          - fullstackdemo-backend.local


networks:
  fullstackdemo:

volumes:
  fullstack_demo_pg_data:
